server:
  port: 10010
spring:
  application:
    name: ganji-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5  #每5秒进行一次拉取服务列表
zuul:
  prefix: /api   #路由前缀
  routes:
    item-service: /item/**   #商品为服务的映射路径


