server:
  port: 8085
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
ganji:
  jwt:
    secret: leyousheudniisj  #登录验证的秘钥
    pubKeyPath: /Users/liudengke/makeRSA/pub.key       #公钥地址
    priKeyPath: /Users/liudengke/makeRSA/pri.key     #私钥地址
    expire: 30    #过期时间，单位分钟
    cookieName: LY_TOKEN