server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql:///leyou
    hikari:
      maximum-pool-size: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5   #每隔5秒就发送一次心跳
    lease-expiration-duration-in-seconds: 10   #10秒不发动心跳就过期
