server:
  port: 10086
spring:
  application:
    name: ganji-register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    fetch-registry: false  #拉取eureka服务信息
    register-with-eureka: false  #把自己注册到eureka服务列表
  server:
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 5000   #每隔5秒钟进行一次服务列表的清理
